spring.application.name=paymybuddy

spring.datasource.url=JDBC:mysql://192.168.127.128:3306/paymybuddy2?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.security=DEBUG

jwt.secret=o0mltyesYznl/Tt400fSFDZ28TYBT68mqbAj6zW+pDo=



